# Generated by Django 4.0.5 on 2022-06-26 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Userdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True)),
                ('url', models.CharField(max_length=30, null=True)),
                ('phone', models.CharField(max_length=20, null=True)),
            ],
            options={
                'db_table': 'dbuser',
            },
        ),
    ]
